name = ""
license = "MIT"
licenselink = ""
description = ""
homepage = "https://github.com/nguyenkien0703"
demosite = "https://www.linkedin.com/in/kien-nguyen-van-a6a72225b/"
tags = [
    "archive",
    "blog",
    "bootstrap",
    "dark",
    "dark mode",
    "docs",
    "gallery",
    "landing",
    "multilingual",
    "personal",
    "responsive"
]
features = ["search", "flexible", "modular"]
[author]
name = ""
homepage = "https://www.linkedin.com/in/kien-nguyen-van-a6a72225b/"
